# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.25)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS podio::podio podio::podioDict podio::podioRootIO podio::podioRootIODict podio::podio_test_hashes)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target podio::podio
add_library(podio::podio SHARED IMPORTED)

set_target_properties(podio::podio PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/tsai/eic/podio.src/include"
)

# Create imported target podio::podioDict
add_library(podio::podioDict SHARED IMPORTED)

set_target_properties(podio::podioDict PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/tsai/eic/podio.src/include"
  INTERFACE_LINK_LIBRARIES "podio::podio;podio::podio;ROOT::Core;ROOT::Tree"
)

# Create imported target podio::podioRootIO
add_library(podio::podioRootIO SHARED IMPORTED)

set_target_properties(podio::podioRootIO PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PODIO_ENABLE_RNTUPLE=0"
  INTERFACE_INCLUDE_DIRECTORIES "/home/tsai/eic/podio.src/include"
  INTERFACE_LINK_LIBRARIES "podio::podio;ROOT::Core;ROOT::RIO;ROOT::Tree"
)

# Create imported target podio::podioRootIODict
add_library(podio::podioRootIODict SHARED IMPORTED)

set_target_properties(podio::podioRootIODict PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/tsai/eic/podio.src/include"
  INTERFACE_LINK_LIBRARIES "podio::podioRootIO;podio::podio;ROOT::Core;ROOT::Tree"
)

# Create imported target podio::podio_test_hashes
add_executable(podio::podio_test_hashes IMPORTED)

# Import target "podio::podio" for configuration "RelWithDebInfo"
set_property(TARGET podio::podio APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(podio::podio PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/tsai/eic/podio.build/src/libpodio.so"
  IMPORTED_SONAME_RELWITHDEBINFO "libpodio.so"
  )

# Import target "podio::podioDict" for configuration "RelWithDebInfo"
set_property(TARGET podio::podioDict APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(podio::podioDict PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/tsai/eic/podio.build/src/libpodioDict.so"
  IMPORTED_SONAME_RELWITHDEBINFO "libpodioDict.so"
  )

# Import target "podio::podioRootIO" for configuration "RelWithDebInfo"
set_property(TARGET podio::podioRootIO APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(podio::podioRootIO PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/tsai/eic/podio.build/src/libpodioRootIO.so"
  IMPORTED_SONAME_RELWITHDEBINFO "libpodioRootIO.so"
  )

# Import target "podio::podioRootIODict" for configuration "RelWithDebInfo"
set_property(TARGET podio::podioRootIODict APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(podio::podioRootIODict PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/tsai/eic/podio.build/src/libpodioRootIODict.so"
  IMPORTED_SONAME_RELWITHDEBINFO "libpodioRootIODict.so"
  )

# Import target "podio::podio_test_hashes" for configuration "RelWithDebInfo"
set_property(TARGET podio::podio_test_hashes APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(podio::podio_test_hashes PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/tsai/eic/podio.build/src/podio_test_hashes"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
