# CMake generated Testfile for 
# Source directory: /home/tsai/eic/podio.src/tools
# Build directory: /home/tsai/eic/podio.build/tools
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(podio-vis-help "./podio-vis" "--help")
set_tests_properties(podio-vis-help PROPERTIES  DEPENDS "_dummy_target_" ENVIRONMENT "LD_LIBRARY_PATH=/home/tsai/eic/podio.build/tests:/home/tsai/eic/podio.build/src:/usr/local/lib/root::/opt/detector/epic-nightly/lib:/usr/local/lib64:/usr/local/lib;PYTHONPATH=/home/tsai/eic/podio.src/python:/usr/local/python:/usr/local/lib/root:/usr/local/lib/python3.10/site-packages;PODIO_SIOBLOCK_PATH=/home/tsai/eic/podio.build/tests;ROOT_INCLUDE_PATH=/home/tsai/eic/podio.build/tests/datamodel:/home/tsai/eic/podio.src/include;SKIP_SIO_TESTS=1;IO_HANDLERS=ROOT;PODIO_USE_CLANG_FORMAT=OFF;PODIO_BASE=/home/tsai/eic/podio.src;ENABLE_SIO=OFF;PODIO_BUILD_BASE=/home/tsai/eic/podio.build" WORKING_DIRECTORY "/home/tsai/eic/podio.src/tools" _BACKTRACE_TRIPLES "/home/tsai/eic/podio.src/tools/CMakeLists.txt;16;add_test;/home/tsai/eic/podio.src/tools/CMakeLists.txt;29;CREATE_VIS_TEST;/home/tsai/eic/podio.src/tools/CMakeLists.txt;0;")
add_test(podio-vis-datamodel "./podio-vis" "--dot" "/home/tsai/eic/podio.src/tests/datalayout.yaml")
set_tests_properties(podio-vis-datamodel PROPERTIES  DEPENDS "datamodel" ENVIRONMENT "LD_LIBRARY_PATH=/home/tsai/eic/podio.build/tests:/home/tsai/eic/podio.build/src:/usr/local/lib/root::/opt/detector/epic-nightly/lib:/usr/local/lib64:/usr/local/lib;PYTHONPATH=/home/tsai/eic/podio.src/python:/usr/local/python:/usr/local/lib/root:/usr/local/lib/python3.10/site-packages;PODIO_SIOBLOCK_PATH=/home/tsai/eic/podio.build/tests;ROOT_INCLUDE_PATH=/home/tsai/eic/podio.build/tests/datamodel:/home/tsai/eic/podio.src/include;SKIP_SIO_TESTS=1;IO_HANDLERS=ROOT;PODIO_USE_CLANG_FORMAT=OFF;PODIO_BASE=/home/tsai/eic/podio.src;ENABLE_SIO=OFF;PODIO_BUILD_BASE=/home/tsai/eic/podio.build" WORKING_DIRECTORY "/home/tsai/eic/podio.src/tools" _BACKTRACE_TRIPLES "/home/tsai/eic/podio.src/tools/CMakeLists.txt;16;add_test;/home/tsai/eic/podio.src/tools/CMakeLists.txt;31;CREATE_VIS_TEST;/home/tsai/eic/podio.src/tools/CMakeLists.txt;0;")
add_test(podio-vis-datamodel-extension "./podio-vis" "--dot" "--upstream-edm" "datamodel:/home/tsai/eic/podio.src/tests/datalayout.yaml" "/home/tsai/eic/podio.src/tests/datalayout_extension.yaml")
set_tests_properties(podio-vis-datamodel-extension PROPERTIES  DEPENDS "extension_model" ENVIRONMENT "LD_LIBRARY_PATH=/home/tsai/eic/podio.build/tests:/home/tsai/eic/podio.build/src:/usr/local/lib/root::/opt/detector/epic-nightly/lib:/usr/local/lib64:/usr/local/lib;PYTHONPATH=/home/tsai/eic/podio.src/python:/usr/local/python:/usr/local/lib/root:/usr/local/lib/python3.10/site-packages;PODIO_SIOBLOCK_PATH=/home/tsai/eic/podio.build/tests;ROOT_INCLUDE_PATH=/home/tsai/eic/podio.build/tests/datamodel:/home/tsai/eic/podio.src/include;SKIP_SIO_TESTS=1;IO_HANDLERS=ROOT;PODIO_USE_CLANG_FORMAT=OFF;PODIO_BASE=/home/tsai/eic/podio.src;ENABLE_SIO=OFF;PODIO_BUILD_BASE=/home/tsai/eic/podio.build" WORKING_DIRECTORY "/home/tsai/eic/podio.src/tools" _BACKTRACE_TRIPLES "/home/tsai/eic/podio.src/tools/CMakeLists.txt;16;add_test;/home/tsai/eic/podio.src/tools/CMakeLists.txt;33;CREATE_VIS_TEST;/home/tsai/eic/podio.src/tools/CMakeLists.txt;0;")
add_test(podio-dump-help "./podio-dump" "--help")
set_tests_properties(podio-dump-help PROPERTIES  DEPENDS "_dummy_target_" ENVIRONMENT "LD_LIBRARY_PATH=/home/tsai/eic/podio.build/tests:/home/tsai/eic/podio.build/src:/usr/local/lib/root::/opt/detector/epic-nightly/lib:/usr/local/lib64:/usr/local/lib;PYTHONPATH=/home/tsai/eic/podio.src/python:/usr/local/python:/usr/local/lib/root:/usr/local/lib/python3.10/site-packages;PODIO_SIOBLOCK_PATH=/home/tsai/eic/podio.build/tests;ROOT_INCLUDE_PATH=/home/tsai/eic/podio.build/tests/datamodel:/home/tsai/eic/podio.src/include;SKIP_SIO_TESTS=1;IO_HANDLERS=ROOT;PODIO_USE_CLANG_FORMAT=OFF;PODIO_BASE=/home/tsai/eic/podio.src;ENABLE_SIO=OFF;PODIO_BUILD_BASE=/home/tsai/eic/podio.build" WORKING_DIRECTORY "/home/tsai/eic/podio.src/tools" _BACKTRACE_TRIPLES "/home/tsai/eic/podio.src/tools/CMakeLists.txt;46;add_test;/home/tsai/eic/podio.src/tools/CMakeLists.txt;80;CREATE_DUMP_TEST;/home/tsai/eic/podio.src/tools/CMakeLists.txt;0;")
add_test(podio-dump-root "./podio-dump" "/home/tsai/eic/podio.build/tests/root_io/example_frame.root")
set_tests_properties(podio-dump-root PROPERTIES  DEPENDS "write_frame_root" ENVIRONMENT "LD_LIBRARY_PATH=/home/tsai/eic/podio.build/tests:/home/tsai/eic/podio.build/src:/usr/local/lib/root::/opt/detector/epic-nightly/lib:/usr/local/lib64:/usr/local/lib;PYTHONPATH=/home/tsai/eic/podio.src/python:/usr/local/python:/usr/local/lib/root:/usr/local/lib/python3.10/site-packages;PODIO_SIOBLOCK_PATH=/home/tsai/eic/podio.build/tests;ROOT_INCLUDE_PATH=/home/tsai/eic/podio.build/tests/datamodel:/home/tsai/eic/podio.src/include;SKIP_SIO_TESTS=1;IO_HANDLERS=ROOT;PODIO_USE_CLANG_FORMAT=OFF;PODIO_BASE=/home/tsai/eic/podio.src;ENABLE_SIO=OFF;PODIO_BUILD_BASE=/home/tsai/eic/podio.build" WORKING_DIRECTORY "/home/tsai/eic/podio.src/tools" _BACKTRACE_TRIPLES "/home/tsai/eic/podio.src/tools/CMakeLists.txt;46;add_test;/home/tsai/eic/podio.src/tools/CMakeLists.txt;81;CREATE_DUMP_TEST;/home/tsai/eic/podio.src/tools/CMakeLists.txt;0;")
add_test(podio-dump-detailed-root "./podio-dump" "--detailed" "--category" "other_events" "--entries" "2:3" "/home/tsai/eic/podio.build/tests/root_io/example_frame.root")
set_tests_properties(podio-dump-detailed-root PROPERTIES  DEPENDS "write_frame_root" ENVIRONMENT "LD_LIBRARY_PATH=/home/tsai/eic/podio.build/tests:/home/tsai/eic/podio.build/src:/usr/local/lib/root::/opt/detector/epic-nightly/lib:/usr/local/lib64:/usr/local/lib;PYTHONPATH=/home/tsai/eic/podio.src/python:/usr/local/python:/usr/local/lib/root:/usr/local/lib/python3.10/site-packages;PODIO_SIOBLOCK_PATH=/home/tsai/eic/podio.build/tests;ROOT_INCLUDE_PATH=/home/tsai/eic/podio.build/tests/datamodel:/home/tsai/eic/podio.src/include;SKIP_SIO_TESTS=1;IO_HANDLERS=ROOT;PODIO_USE_CLANG_FORMAT=OFF;PODIO_BASE=/home/tsai/eic/podio.src;ENABLE_SIO=OFF;PODIO_BUILD_BASE=/home/tsai/eic/podio.build" WORKING_DIRECTORY "/home/tsai/eic/podio.src/tools" _BACKTRACE_TRIPLES "/home/tsai/eic/podio.src/tools/CMakeLists.txt;46;add_test;/home/tsai/eic/podio.src/tools/CMakeLists.txt;82;CREATE_DUMP_TEST;/home/tsai/eic/podio.src/tools/CMakeLists.txt;0;")
add_test(podio-dump-legacy_root_v00-16-06 "./podio-dump" "/home/tsai/eic/podio.build/tests/input_files/v00-16-06-example.root")
set_tests_properties(podio-dump-legacy_root_v00-16-06 PROPERTIES  ENVIRONMENT "LD_LIBRARY_PATH=/home/tsai/eic/podio.build/tests:/home/tsai/eic/podio.build/src:/usr/local/lib/root::/opt/detector/epic-nightly/lib:/usr/local/lib64:/usr/local/lib;PYTHONPATH=/home/tsai/eic/podio.src/python:/usr/local/python:/usr/local/lib/root:/usr/local/lib/python3.10/site-packages;PODIO_SIOBLOCK_PATH=/home/tsai/eic/podio.build/tests;ROOT_INCLUDE_PATH=/home/tsai/eic/podio.build/tests/datamodel:/home/tsai/eic/podio.src/include;SKIP_SIO_TESTS=1;IO_HANDLERS=ROOT;PODIO_USE_CLANG_FORMAT=OFF;PODIO_BASE=/home/tsai/eic/podio.src;ENABLE_SIO=OFF;PODIO_BUILD_BASE=/home/tsai/eic/podio.build" WORKING_DIRECTORY "/home/tsai/eic/podio.src/tools" _BACKTRACE_TRIPLES "/opt/software/linux-debian12-x86_64_v2/gcc-12.2.0/cmake-3.27.7-pri2k5ipo2u4nthvxsyude622zxoomt3/share/cmake-3.27/Modules/ExternalData.cmake;356;add_test;/home/tsai/eic/podio.src/tools/CMakeLists.txt;69;ExternalData_Add_Test;/home/tsai/eic/podio.src/tools/CMakeLists.txt;84;CREATE_LEGACY_DUMP_TEST;/home/tsai/eic/podio.src/tools/CMakeLists.txt;0;")
add_test(podio-dump-legacy_root-detailed_v00-16-06 "./podio-dump" "--detailed" "--entries" "2:3" "/home/tsai/eic/podio.build/tests/input_files/v00-16-06-example.root")
set_tests_properties(podio-dump-legacy_root-detailed_v00-16-06 PROPERTIES  ENVIRONMENT "LD_LIBRARY_PATH=/home/tsai/eic/podio.build/tests:/home/tsai/eic/podio.build/src:/usr/local/lib/root::/opt/detector/epic-nightly/lib:/usr/local/lib64:/usr/local/lib;PYTHONPATH=/home/tsai/eic/podio.src/python:/usr/local/python:/usr/local/lib/root:/usr/local/lib/python3.10/site-packages;PODIO_SIOBLOCK_PATH=/home/tsai/eic/podio.build/tests;ROOT_INCLUDE_PATH=/home/tsai/eic/podio.build/tests/datamodel:/home/tsai/eic/podio.src/include;SKIP_SIO_TESTS=1;IO_HANDLERS=ROOT;PODIO_USE_CLANG_FORMAT=OFF;PODIO_BASE=/home/tsai/eic/podio.src;ENABLE_SIO=OFF;PODIO_BUILD_BASE=/home/tsai/eic/podio.build" WORKING_DIRECTORY "/home/tsai/eic/podio.src/tools" _BACKTRACE_TRIPLES "/opt/software/linux-debian12-x86_64_v2/gcc-12.2.0/cmake-3.27.7-pri2k5ipo2u4nthvxsyude622zxoomt3/share/cmake-3.27/Modules/ExternalData.cmake;356;add_test;/home/tsai/eic/podio.src/tools/CMakeLists.txt;69;ExternalData_Add_Test;/home/tsai/eic/podio.src/tools/CMakeLists.txt;85;CREATE_LEGACY_DUMP_TEST;/home/tsai/eic/podio.src/tools/CMakeLists.txt;0;")
