# CMake generated Testfile for 
# Source directory: /home/tsai/eic/podio.src/tests/dumpmodel
# Build directory: /home/tsai/eic/podio.build/tests/dumpmodel
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(datamodel_def_store_roundtrip_root "/home/tsai/eic/podio.src/tests/scripts/dumpModelRoundTrip.sh" "/home/tsai/eic/podio.build/tests/root_io/example_frame.root" "datamodel" "/home/tsai/eic/podio.src/tests")
set_tests_properties(datamodel_def_store_roundtrip_root PROPERTIES  DEPENDS "write_frame_root" ENVIRONMENT "LD_LIBRARY_PATH=/home/tsai/eic/podio.build/tests:/home/tsai/eic/podio.build/src:/usr/local/lib/root::/opt/detector/epic-nightly/lib:/usr/local/lib64:/usr/local/lib;PYTHONPATH=/home/tsai/eic/podio.src/python:/usr/local/python:/usr/local/lib/root:/usr/local/lib/python3.10/site-packages;PODIO_SIOBLOCK_PATH=/home/tsai/eic/podio.build/tests;ROOT_INCLUDE_PATH=/home/tsai/eic/podio.build/tests/datamodel:/home/tsai/eic/podio.src/include;SKIP_SIO_TESTS=1;IO_HANDLERS=ROOT;PODIO_USE_CLANG_FORMAT=OFF;PODIO_BASE=/home/tsai/eic/podio.src;ENABLE_SIO=OFF;PODIO_BUILD_BASE=/home/tsai/eic/podio.build" WORKING_DIRECTORY "/home/tsai/eic/podio.build/tests/dumpmodel" _BACKTRACE_TRIPLES "/home/tsai/eic/podio.src/tests/dumpmodel/CMakeLists.txt;6;add_test;/home/tsai/eic/podio.src/tests/dumpmodel/CMakeLists.txt;0;")
add_test(datamodel_def_store_roundtrip_root_extension "/home/tsai/eic/podio.src/tests/scripts/dumpModelRoundTrip.sh" "/home/tsai/eic/podio.build/tests/root_io/example_frame.root" "extension_model" "/home/tsai/eic/podio.src/tests/extension_model" "--upstream-edm=datamodel:/home/tsai/eic/podio.src/tests/datalayout.yaml")
set_tests_properties(datamodel_def_store_roundtrip_root_extension PROPERTIES  DEPENDS "write_frame_root" ENVIRONMENT "LD_LIBRARY_PATH=/home/tsai/eic/podio.build/tests:/home/tsai/eic/podio.build/src:/usr/local/lib/root::/opt/detector/epic-nightly/lib:/usr/local/lib64:/usr/local/lib;PYTHONPATH=/home/tsai/eic/podio.src/python:/usr/local/python:/usr/local/lib/root:/usr/local/lib/python3.10/site-packages;PODIO_SIOBLOCK_PATH=/home/tsai/eic/podio.build/tests;ROOT_INCLUDE_PATH=/home/tsai/eic/podio.build/tests/datamodel:/home/tsai/eic/podio.src/include;SKIP_SIO_TESTS=1;IO_HANDLERS=ROOT;PODIO_USE_CLANG_FORMAT=OFF;PODIO_BASE=/home/tsai/eic/podio.src;ENABLE_SIO=OFF;PODIO_BUILD_BASE=/home/tsai/eic/podio.build" WORKING_DIRECTORY "/home/tsai/eic/podio.build/tests/dumpmodel" _BACKTRACE_TRIPLES "/home/tsai/eic/podio.src/tests/dumpmodel/CMakeLists.txt;14;add_test;/home/tsai/eic/podio.src/tests/dumpmodel/CMakeLists.txt;0;")
