apiVersion: v1
kind: Pod
metadata:
  name: tcp2podio{{ .Values.name }}
  namespace: "{{ .Values.namespace }}"
spec:
  containers:
    - name: wf
      image: wf
      command: ["bash"]
      args: [""]
      volumeMounts:
        - name: wf
          mountPath: wf
      resources:
        limits:
          cpu: "256"
        requests:
          cpu: "256"

    - name: prom
      image: prom
      command: ["bash"]
      args: [""]
      env:
        - name: PGID_FILE
          value: "~/100g/tcp2podio{{ .Values.name }}/containers/wf/pgid"
        - name: PROCESS_EXPORTER_PORT
          value: "{{ .Values.prometheus_settings.process_exporter_port }}"

      volumeMounts:
        - name: prom
          mountPath: prom
      # resources:
      #   limits:
      #     cpu: "32"
      #     memory: 128Gi

  volumes:
    - name: wf
      configMap:
        name: wf{{ .Values.name }}
    - name: prom
      configMap:
        name: prom{{ .Values.name }}
        
  nodeSelector:
    kubernetes.io/role: agent
    kubernetes.io/hostname: vk-nersc
  tolerations:
    - key: "virtual-kubelet.io/provider"
      value: "mock"
      effect: "NoSchedule"
