apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Deployment.name}}
  namespace: {{ .Values.Deployment.namespace}}
  labels:
    app: {{ .Values.Deployment.name}}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.Deployment.name}}
  ports: [{{- range $index, $element := .Values.Service }}
    {{- if $index }},{{ end }}
    {
      name: {{ printf "%s-%s" $element.name $element.node | quote }},      
      protocol: {{ $element.protocol | quote }},
      port: {{ $element.port }},
      targetPort: {{ $element.port }}
    }
    {{- end }}]