apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-{{ .Values.Deployment.name}}
spec:
  capacity:
    storage: {{ .Values.PersistentVolume.size}}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-{{ .Values.Deployment.name}}
  local:
    path: "{{ .Values.PersistentVolume.path}}/{{ .Values.Deployment.name}}"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.PersistentVolume.node}}