#!/bin/bash
#
#

git clone https://github.com/JeffersonLab/SRO-RTDP




cmake -S SRO-RTDP/src/utilities/cpp/podiostream -B podiostream.build \
    -DCMAKE_POLICY_DEFAULT_CMP0074=NEW \
    -DCMAKE_CXX_STANDARD=20

cmake --build podiostream.build

echo ${JANA_PLUGIN_PATH}

export JANA_PLUGIN_PATH=${PWD}/podiostream.build:${JANA_PLUGIN_PATH}