# CMake generated Testfile for 
# Source directory: /home/tsai/eic/podio.src/tests/schema_evolution/root_io
# Build directory: /home/tsai/eic/podio.build/tests/schema_evolution/root_io
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(write_old_data_root "/home/tsai/eic/podio.build/tests/schema_evolution/root_io/write_old_data_root")
set_tests_properties(write_old_data_root PROPERTIES  ENVIRONMENT "LD_LIBRARY_PATH=/home/tsai/eic/podio.build/tests:/home/tsai/eic/podio.build/src:/usr/local/lib/root::/opt/detector/epic-nightly/lib:/usr/local/lib64:/usr/local/lib;PYTHONPATH=/home/tsai/eic/podio.src/python:/usr/local/python:/usr/local/lib/root:/usr/local/lib/python3.10/site-packages;PODIO_SIOBLOCK_PATH=/home/tsai/eic/podio.build/tests;ROOT_INCLUDE_PATH=/home/tsai/eic/podio.build/tests/datamodel:/home/tsai/eic/podio.src/include;SKIP_SIO_TESTS=1;IO_HANDLERS=ROOT;PODIO_USE_CLANG_FORMAT=OFF;PODIO_BASE=/home/tsai/eic/podio.src;ENABLE_SIO=OFF;PODIO_BUILD_BASE=/home/tsai/eic/podio.build" _BACKTRACE_TRIPLES "/home/tsai/eic/podio.src/cmake/podioTest.cmake;27;add_test;/home/tsai/eic/podio.src/tests/schema_evolution/root_io/CMakeLists.txt;1;CREATE_PODIO_TEST;/home/tsai/eic/podio.src/tests/schema_evolution/root_io/CMakeLists.txt;0;")
add_test(read_new_data_root "/home/tsai/eic/podio.build/tests/schema_evolution/root_io/read_new_data_root")
set_tests_properties(read_new_data_root PROPERTIES  DEPENDS "write_old_data_root" ENVIRONMENT "LD_LIBRARY_PATH=/home/tsai/eic/podio.build/src:/home/tsai/eic/podio.build/tests/schema_evolution:/usr/local/lib/root::/opt/detector/epic-nightly/lib:/usr/local/lib64:/usr/local/lib;PODIO_SIO_BLOCK=/home/tsai/eic/podio.build/tests/schema_evolution/root_io;ROOT_INCLUDE_PATH=/home/tsai/eic/podio.build/tests/schema_evolution/datamodel_new:/home/tsai/eic/podio.src/include" _BACKTRACE_TRIPLES "/home/tsai/eic/podio.src/tests/schema_evolution/CMakeLists.txt;23;add_test;/home/tsai/eic/podio.src/tests/schema_evolution/root_io/CMakeLists.txt;2;PODIO_CREATE_READ_NEW_DATA_TEST;/home/tsai/eic/podio.src/tests/schema_evolution/root_io/CMakeLists.txt;0;")
