Deployment:
  name: this-name-is-changing
  namespace: default
  replicas: 1
  serviceMonitorLabel: EICrecon # this is the label for the serviceMonitor. It can be the same for multiple deployments if using a single prometheus instance.

  job:
    image: jlabtsai/eic:latest
    cmd: /bin/bash -c /app/run-EICrecon.bash

Service:
- name: jrm-exporter
  protocol: TCP
  port:  10000
  originalPort: 10000
  path: /metrics/resource
  interval: 30s
- name: process-exporter
  node: "0"
  protocol: TCP
  port:  20000
  originalPort: 1776
  path: /metrics
  interval: 30s


PersistentVolume:
  node: jiriaf2302-control-plane
  path: /var/prom
  size: 5Gi
Prometheus:
  serviceaccount: prometheus-k8s
  namespace: monitoring

#https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/customizations/monitoring-additional-namespaces.md