# CMake generated Testfile for 
# Source directory: /home/tsai/eic/podio.src/python
# Build directory: /home/tsai/eic/podio.build/python
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(pyunittest "python3" "-m" "unittest" "discover" "-s" "/home/tsai/eic/podio.src/python/podio")
set_tests_properties(pyunittest PROPERTIES  DEPENDS "write;write_frame_root" ENVIRONMENT "LD_LIBRARY_PATH=/home/tsai/eic/podio.build/tests:/home/tsai/eic/podio.build/src:/usr/local/lib/root::/opt/detector/epic-nightly/lib:/usr/local/lib64:/usr/local/lib;PYTHONPATH=/home/tsai/eic/podio.src/python:/usr/local/python:/usr/local/lib/root:/usr/local/lib/python3.10/site-packages;PODIO_SIOBLOCK_PATH=/home/tsai/eic/podio.build/tests;ROOT_INCLUDE_PATH=/home/tsai/eic/podio.build/tests/datamodel:/home/tsai/eic/podio.src/include;SKIP_SIO_TESTS=1;IO_HANDLERS=ROOT;PODIO_USE_CLANG_FORMAT=OFF;PODIO_BASE=/home/tsai/eic/podio.src;ENABLE_SIO=OFF;PODIO_BUILD_BASE=/home/tsai/eic/podio.build" WORKING_DIRECTORY "/home/tsai/eic/podio.build/tests" _BACKTRACE_TRIPLES "/home/tsai/eic/podio.src/python/CMakeLists.txt;43;add_test;/home/tsai/eic/podio.src/python/CMakeLists.txt;0;")
add_test(pyunittest_gen "python3" "-m" "unittest" "discover" "-s" "/home/tsai/eic/podio.src/python/podio_gen")
set_tests_properties(pyunittest_gen PROPERTIES  ENVIRONMENT "LD_LIBRARY_PATH=/home/tsai/eic/podio.build/tests:/home/tsai/eic/podio.build/src:/usr/local/lib/root::/opt/detector/epic-nightly/lib:/usr/local/lib64:/usr/local/lib;PYTHONPATH=/home/tsai/eic/podio.src/python:/usr/local/python:/usr/local/lib/root:/usr/local/lib/python3.10/site-packages;PODIO_SIOBLOCK_PATH=/home/tsai/eic/podio.build/tests;ROOT_INCLUDE_PATH=/home/tsai/eic/podio.build/tests/datamodel:/home/tsai/eic/podio.src/include;SKIP_SIO_TESTS=1;IO_HANDLERS=ROOT;PODIO_USE_CLANG_FORMAT=OFF;PODIO_BASE=/home/tsai/eic/podio.src;ENABLE_SIO=OFF;PODIO_BUILD_BASE=/home/tsai/eic/podio.build" WORKING_DIRECTORY "/home/tsai/eic/podio.build/tests" _BACKTRACE_TRIPLES "/home/tsai/eic/podio.src/python/CMakeLists.txt;45;add_test;/home/tsai/eic/podio.src/python/CMakeLists.txt;0;")
