apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{.Values.Deployment.name}}
  namespace: {{.Values.Deployment.namespace}}
  labels:
    app: {{.Values.Deployment.name}}
spec:
  selector:
    matchLabels:
      app: {{.Values.Deployment.name}}
  endpoints: []