//
// This file was generated by CMake (see cmake/make_config.cmake)
//

#define JANA2_HAVE_ROOT     1
#define JANA2_HAVE_XERCES   
#define XERCES3       
#define HAVE_CCDB     0
#define HAVE_NUMA     0

