#-- AUTOMATICALLY GENERATED FILE - DO NOT EDIT -- 

# Generated header files
SET(headers
  ${ARG_OUTPUT_FOLDER}/${datamodel}/SimpleStruct.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/NotSoSimpleStruct.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/NamespaceStruct.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/NamespaceStructv2.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/NamespaceInNamespaceStruct.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/StructWithFixedWithTypes.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/CompWithInit.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/EventInfoNewNameCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/EventInfoNewNameData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/EventInfoNewName.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/MutableEventInfoNewName.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/EventInfoNewNameObj.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/EventInfoNewNameCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/EventInfoNewNameCollectionData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleHitCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleHitData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleHit.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/MutableExampleHit.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleHitObj.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleHitCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleHitCollectionData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleMCCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleMCData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleMC.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/MutableExampleMC.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleMCObj.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleMCCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleMCCollectionData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleClusterCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleClusterData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleCluster.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/MutableExampleCluster.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleClusterObj.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleClusterCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleClusterCollectionData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleReferencingTypeCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleReferencingTypeData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleReferencingType.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/MutableExampleReferencingType.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleReferencingTypeObj.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleReferencingTypeCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleReferencingTypeCollectionData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithVectorMemberCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithVectorMemberData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithVectorMember.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/MutableExampleWithVectorMember.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithVectorMemberObj.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithVectorMemberCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithVectorMemberCollectionData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithOneRelationCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithOneRelationData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithOneRelation.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/MutableExampleWithOneRelation.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithOneRelationObj.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithOneRelationCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithOneRelationCollectionData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithArrayComponentCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithArrayComponentData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithArrayComponent.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/MutableExampleWithArrayComponent.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithArrayComponentObj.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithArrayComponentCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithArrayComponentCollectionData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithComponentCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithComponentData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithComponent.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/MutableExampleWithComponent.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithComponentObj.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithComponentCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithComponentCollectionData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleForCyclicDependency1Collection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleForCyclicDependency1Data.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleForCyclicDependency1.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/MutableExampleForCyclicDependency1.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleForCyclicDependency1Obj.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleForCyclicDependency1Collection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleForCyclicDependency1CollectionData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleForCyclicDependency2Collection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleForCyclicDependency2Data.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleForCyclicDependency2.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/MutableExampleForCyclicDependency2.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleForCyclicDependency2Obj.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleForCyclicDependency2Collection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleForCyclicDependency2CollectionData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithNamespacev2Data.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithNamespaceCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithNamespaceData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithNamespace.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/MutableExampleWithNamespace.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithNamespaceObj.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithNamespaceCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithNamespaceCollectionData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithARelationCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithARelationData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithARelation.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/MutableExampleWithARelation.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithARelationObj.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithARelationCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithARelationCollectionData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithDifferentNamespaceRelationsCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithDifferentNamespaceRelationsData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithDifferentNamespaceRelations.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/MutableExampleWithDifferentNamespaceRelations.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithDifferentNamespaceRelationsObj.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithDifferentNamespaceRelationsCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithDifferentNamespaceRelationsCollectionData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithArrayv2Data.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithArrayCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithArrayData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithArray.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/MutableExampleWithArray.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithArrayObj.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithArrayCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithArrayCollectionData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithFixedWidthIntegersCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithFixedWidthIntegersData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithFixedWidthIntegers.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/MutableExampleWithFixedWidthIntegers.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithFixedWidthIntegersObj.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithFixedWidthIntegersCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithFixedWidthIntegersCollectionData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithUserInitv2Data.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithUserInitCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithUserInitData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithUserInit.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/MutableExampleWithUserInit.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithUserInitObj.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithUserInitCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleWithUserInitCollectionData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleOfDroppedTypeCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleOfDroppedTypeData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleOfDroppedType.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/MutableExampleOfDroppedType.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleOfDroppedTypeObj.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleOfDroppedTypeCollection.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/ExampleOfDroppedTypeCollectionData.h
  ${ARG_OUTPUT_FOLDER}/${datamodel}/DatamodelDefinition.h
)
# Generated source files
SET(sources
  ${ARG_OUTPUT_FOLDER}/src/SimpleStruct.cc
  ${ARG_OUTPUT_FOLDER}/src/NotSoSimpleStruct.cc
  ${ARG_OUTPUT_FOLDER}/src/NamespaceStruct.cc
  ${ARG_OUTPUT_FOLDER}/src/NamespaceStructv2.cc
  ${ARG_OUTPUT_FOLDER}/src/NamespaceInNamespaceStruct.cc
  ${ARG_OUTPUT_FOLDER}/src/StructWithFixedWithTypes.cc
  ${ARG_OUTPUT_FOLDER}/src/CompWithInit.cc
  ${ARG_OUTPUT_FOLDER}/src/EventInfoNewNameCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/EventInfoNewName.cc
  ${ARG_OUTPUT_FOLDER}/src/MutableEventInfoNewName.cc
  ${ARG_OUTPUT_FOLDER}/src/EventInfoNewNameObj.cc
  ${ARG_OUTPUT_FOLDER}/src/EventInfoNewNameCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/EventInfoNewNameCollectionData.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleHitCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleHit.cc
  ${ARG_OUTPUT_FOLDER}/src/MutableExampleHit.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleHitObj.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleHitCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleHitCollectionData.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleMCCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleMC.cc
  ${ARG_OUTPUT_FOLDER}/src/MutableExampleMC.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleMCObj.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleMCCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleMCCollectionData.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleClusterCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleCluster.cc
  ${ARG_OUTPUT_FOLDER}/src/MutableExampleCluster.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleClusterObj.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleClusterCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleClusterCollectionData.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleReferencingTypeCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleReferencingType.cc
  ${ARG_OUTPUT_FOLDER}/src/MutableExampleReferencingType.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleReferencingTypeObj.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleReferencingTypeCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleReferencingTypeCollectionData.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithVectorMemberCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithVectorMember.cc
  ${ARG_OUTPUT_FOLDER}/src/MutableExampleWithVectorMember.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithVectorMemberObj.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithVectorMemberCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithVectorMemberCollectionData.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithOneRelationCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithOneRelation.cc
  ${ARG_OUTPUT_FOLDER}/src/MutableExampleWithOneRelation.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithOneRelationObj.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithOneRelationCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithOneRelationCollectionData.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithArrayComponentCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithArrayComponent.cc
  ${ARG_OUTPUT_FOLDER}/src/MutableExampleWithArrayComponent.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithArrayComponentObj.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithArrayComponentCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithArrayComponentCollectionData.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithComponentCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithComponent.cc
  ${ARG_OUTPUT_FOLDER}/src/MutableExampleWithComponent.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithComponentObj.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithComponentCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithComponentCollectionData.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleForCyclicDependency1Collection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleForCyclicDependency1.cc
  ${ARG_OUTPUT_FOLDER}/src/MutableExampleForCyclicDependency1.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleForCyclicDependency1Obj.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleForCyclicDependency1Collection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleForCyclicDependency1CollectionData.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleForCyclicDependency2Collection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleForCyclicDependency2.cc
  ${ARG_OUTPUT_FOLDER}/src/MutableExampleForCyclicDependency2.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleForCyclicDependency2Obj.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleForCyclicDependency2Collection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleForCyclicDependency2CollectionData.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithNamespaceCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithNamespace.cc
  ${ARG_OUTPUT_FOLDER}/src/MutableExampleWithNamespace.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithNamespaceObj.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithNamespaceCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithNamespaceCollectionData.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithARelationCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithARelation.cc
  ${ARG_OUTPUT_FOLDER}/src/MutableExampleWithARelation.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithARelationObj.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithARelationCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithARelationCollectionData.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithDifferentNamespaceRelationsCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithDifferentNamespaceRelations.cc
  ${ARG_OUTPUT_FOLDER}/src/MutableExampleWithDifferentNamespaceRelations.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithDifferentNamespaceRelationsObj.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithDifferentNamespaceRelationsCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithDifferentNamespaceRelationsCollectionData.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithArrayCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithArray.cc
  ${ARG_OUTPUT_FOLDER}/src/MutableExampleWithArray.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithArrayObj.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithArrayCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithArrayCollectionData.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithFixedWidthIntegersCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithFixedWidthIntegers.cc
  ${ARG_OUTPUT_FOLDER}/src/MutableExampleWithFixedWidthIntegers.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithFixedWidthIntegersObj.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithFixedWidthIntegersCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithFixedWidthIntegersCollectionData.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithUserInitCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithUserInit.cc
  ${ARG_OUTPUT_FOLDER}/src/MutableExampleWithUserInit.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithUserInitObj.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithUserInitCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleWithUserInitCollectionData.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleOfDroppedTypeCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleOfDroppedType.cc
  ${ARG_OUTPUT_FOLDER}/src/MutableExampleOfDroppedType.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleOfDroppedTypeObj.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleOfDroppedTypeCollection.cc
  ${ARG_OUTPUT_FOLDER}/src/ExampleOfDroppedTypeCollectionData.cc
)
# Generated xml files
SET(selection_xml
  ${ARG_OUTPUT_FOLDER}/src/selection.xml
)