apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.Deployment.name}}
  namespace: {{ .Values.Deployment.namespace}}
spec:
  parallelism: {{ .Values.Deployment.replicas}}
  template:
    metadata:
      labels:
        app: {{ .Values.Deployment.name}}
    spec:
      containers:
      - name: wf
        image: wf
        command: ["bash"]
        args: [""]
        ports:
        - containerPort: {{ index .Values.Service 0 "originalPort" }}
        volumeMounts:
        - name: wf
          mountPath: wf
        resources:
          limits:
            cpu: "128"
          requests:
            cpu: "128"
      - name: prom
        image: prom
        command: ["bash"]
        args: [""]
        env:
          - name: PROCESS_EXPORTER_PORT
            value: "{{ index .Values.Service 1 "originalPort" }}"
        ports:
          - containerPort: {{ index .Values.Service 1 "originalPort" }}
        volumeMounts:
          - name: prom
            mountPath: prom


      volumes:
      - name: wf
        configMap:
          name: wf-{{ .Values.Deployment.name }}
      - name: prom
        configMap:
          name: prom-{{ .Values.Deployment.name}}

      restartPolicy: OnFailure
      nodeSelector:
        kubernetes.io/role: agent
      tolerations:
      - key: "virtual-kubelet.io/provider"
        value: "mock"
        effect: "NoSchedule"

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: jiriaf.site
                operator: In
                values:
                - "perlmutter"

      