kind: ConfigMap
apiVersion: v1
metadata:
  name: wf-{{ .Values.Deployment.name }}
  namespace: {{ .Values.Deployment.namespace }}
data:
  wf.sh: |
    #!/bin/bash
    
    shifter --image={{ .Values.Deployment.job.image }} {{ .Values.Deployment.job.cmd }}
