kind: ConfigMap
apiVersion: v1
metadata:
  name: wf-{{ .Values.Deployment.name }}
  namespace: {{ .Values.Deployment.namespace }}
data:
  wf.sh: |
    #!/bin/bash
    
    ssh -NfL 5557:localhost:5557 jlabtsai@128.55.64.13
  
    shifter -e WORKDIR=/pscratch/sd/j/jlabtsai --image={{ .Values.Deployment.job.image }} {{ .Values.Deployment.job.cmd }}
